name: Validate PR Changelog (Local)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    uses: ./.github/workflows/validate-changelog.yml
    permissions:
      pull-requests: read
      contents: read
    with:
      changelog-file: CHANGELOG.md
      error-on-template: 'Changelog: patch|minor|major'
      post-version-script: |
        for WORKFLOW in "validate-changelog" "update-changelog" "release"; do
          COMPONENT_PATH="happy-changelog/happy-changelog-workflow/.github/workflows/${WORKFLOW}.yml"
          sed -i "s|${COMPONENT_PATH}@[a-zA-Z0-9._-]*|${COMPONENT_PATH}@v${NEW_VERSION}|g" README.md
        done
        git add README.md
