name: Validate PR Changelog (Local)

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate:
    uses: ./.github/workflows/validate-changelog.yml
    permissions:
      pull-requests: read
      contents: read
    with:
      changelog-file: CHANGELOG.md
      error-on-template: 'Changelog: patch|minor|major'