name: Update Changelog file and version

on:
  workflow_call:
    inputs:
      changelog-file:
        description: 'Path to the changelog file'
        required: false
        type: string
        default: 'CHANGELOG.md'
      enable-npm-version:
        description: 'Update version in package.json'
        required: false
        type: boolean
        default: true
      target-branch:
        description: 'Branch to update changelog on'
        required: false
        type: string
        default: 'main'
      version-title-template:
        description: 'Template for version title (supports {version} and {date})'
        required: false
        type: string
        default: 'v:{version} - {date}'
    outputs:
      new_version:
        description: 'New version number'
        value: ${{ jobs.update-changelog.outputs.new_version }}

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    name: Update Changelog file and version
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.target-branch }}-${{ inputs.changelog-file }}
      cancel-in-progress: true
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Extract changes since last tag
        id: changes
        run: | #shell
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [[ -n "$PREVIOUS_TAG" ]]; then
            GIT_RANGE="${PREVIOUS_TAG}..HEAD"
          else
            GIT_RANGE="HEAD"
          fi

          echo "Previous tag: $PREVIOUS_TAG"
          echo "Git range: $GIT_RANGE"
          
          CHANGE_LEVEL="patch"
          TEMP_FILE=$(mktemp)
          
          for COMMIT in $(git rev-list $GIT_RANGE); do
            COMMIT_MSG=$(git log --format=%B -n 1 $COMMIT)
            
            if echo "$COMMIT_MSG" | grep -q '/changelog\|<details><summary>Changelog'; then
              if echo "$COMMIT_MSG" | grep -q '/changelog'; then
                NOTE=$(echo "$COMMIT_MSG" | sed -n '/\/changelog/,/\/-changelog/p' | grep -v '/changelog')
                LEVEL=$(echo "$COMMIT_MSG" | grep '/changelog' | grep -Eo 'patch|minor|major' || echo "patch")
              else
                NOTE=$(echo "$COMMIT_MSG" | awk '/<details><summary>Changelog/,/<\/details>/' | sed '1d;$d')
                LEVEL=$(echo "$COMMIT_MSG" | grep '<details><summary>Changelog' | grep -Eo 'patch|minor|major' || echo "patch")
              fi
              
              if [[ "$LEVEL" == "major" ]] || [[ "$CHANGE_LEVEL" == "patch" ]]; then
                CHANGE_LEVEL="$LEVEL"
              elif [[ "$LEVEL" == "minor" ]] && [[ "$CHANGE_LEVEL" == "patch" ]]; then
                CHANGE_LEVEL="minor"
              fi
              
              echo "$NOTE" >> $TEMP_FILE
            fi
          done
          
          echo "notes=$(cat $TEMP_FILE)"
          echo "level=$CHANGE_LEVEL"

          echo "level=$CHANGE_LEVEL" >> $GITHUB_OUTPUT
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat $TEMP_FILE >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update changelog file
        if: steps.changes.outputs.notes != ''
        run: | #shell
          if [[ ! -f ${{ inputs.changelog-file }} ]]; then
            echo "# Changelog" > ${{ inputs.changelog-file }}
          fi
          
          CURRENT_DATE=$(date '+%Y-%m-%d')
          TITLE_TEMPLATE="${{ inputs.version-title-template }}"
          FORMATTED_TITLE="${TITLE_TEMPLATE/\{version\}/${{ steps.changes.outputs.level }}}"
          FORMATTED_TITLE="${FORMATTED_TITLE/\{date\}/$CURRENT_DATE}"
          
          npx --yes changelog-tools add ${{ inputs.changelog-file }} \
            -t "$FORMATTED_TITLE" \
            --new-changelog '''${{ steps.changes.outputs.notes }}''' \
            -o ${{ inputs.changelog-file }}

      - name: Update version
        if: steps.changes.outputs.notes != ''
        id: version
        run: | #shell
          NEW_VERSION=$(npx --yes changelog-tools ${{ inputs.changelog-file }} | jq -r '.versions[0].version')
          echo "Updating version..."
          echo "New version: $NEW_VERSION"
          
          if [[ -f package.json ]] && ${{ inputs.enable-npm-version }}; then
            npm version "$NEW_VERSION" --no-git-tag-version
            git add package.json
          fi
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.changes.outputs.notes != ''
        run: | #shell
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ inputs.changelog-file }}
          git commit -m "chore: update changelog - v${{ steps.version.outputs.new_version }}"
          git push origin ${{ inputs.target-branch }}
          git tag -a "v${{ steps.version.outputs.new_version }}" -m "Release v${{ steps.version.outputs.new_version }}"
          git push origin "v${{ steps.version.outputs.new_version }}"
